# Generated by Django 5.2 on 2025-05-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descrition',
            new_name='description',
        ),
    ]
